### ISSUE TITLE
Can you release the rest of code?

### ISSUE THREAD

**Issue by Ttt749** [xaggi/OGNet#1]

**Comment by xaggi** [comment]
Hi.
Due to some restrictions, we are unable to release the code of an ongoing project at this moment. However, we are trying to get around this. Soon after this is resolved, I will upload the rest of the code.

**Comment by Ttt749** [comment]
I try to code the training phase, but I have some questions: 1. why the size of mnist is (45, 45)? 2.when one epoch was completed, the model had already get almost 96%(auc) and the model is not a bad model that can already reconstruct the image. 3. I can't train the code in UCSD ped2 dataset.

**Comment by ron5569** [comment]
Any expectation when the train code will be release?

**Comment by xaggi** [comment]
Hi, a trainable version of the code has been uploaded. Please have a look and let me know if you still face problems.
