### ISSUE TITLE
training for ped2

### ISSUE THREAD

**Issue by songzzs** [xaggi/OGNet#3]
Hi, can you release the code for training ped2? Now there is no code for patching frames of ped2 and how to train patches.

**Comment by BenedictGreen** [comment]
Hi, @songzzs. Have you solve the problem? I had noticed 'a motion detection criteria based on frame difference is set to discard patches without motion.' was mentiond in paper, but I don;t know how to get over it. 
At the same time, I look forward to the author uploading the patch generation code for the ped2 dataset.
Thanks for your great work! @xaggi

**Comment by xaggi** [comment]
Hi, first of all, I apologize for the delay in my response. I have been very busy lately and didn’t get the chance to write a detailed response. The purpose of uploading this code is to give a jumpstart to the researchers who are interested in working on / extending the idea of pseudo anomalies in specific or OGNet in general. Patch extraction functions used in our project are pretty much standard i.e., patches of some dimensions are cropped out without any overlapping. Nevertheless, I will try to upload these functions soon. 

About the motion based criteria for Ped2, several existing papers simply discard the upper regions of the frames where pedestrian motion is usually not present. The idea is to discard the regions where no movement happens within the frames to eliminate unnecessary inference. We attempted to place a similar check by creating a motion detection criteria based on frame difference. To be precise, if pixel values of a given patch do not change at least m% from its corresponding patch in a neighboring frame, we discard it. For ped2, as the fps of the videos is not that high, the value of m is set to 20. 

The apparent benefits: we believe, cropping out a fixed area from the whole dataset may be harmful to the system. For example, we already know that in ped2 (training and testing) no moving subject goes beyond the walkway. However, there is no guarantee that someone will not go there ever. This way, a motion based criteria to discard patches may be more beneficial in the case of such unusual scenarios.
