### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by yty20** [xaggi/OGNet#8]
Hi, I'm running the code with `torch=1.10.1, python=3.9.7, torchvision=0.11.2`, and there is something wrong at the backward.

here is the detailed traceback message:
`Training until high epoch...
[W python_anomaly_mode.cpp:104] Warning: Error detected in AddmmBackward0. Traceback of forward call that caused the error:
  File "/home/yty/lab-code/OGNet/train.py", line 25, in <module>
    model.train(opt.normal_class)
  File "/home/yty/lab-code/OGNet/model.py", line 94, in train
    d_fake_output = self.d(g_output)
  File "/home/yty/anaconda3/envs/svdd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yty/lab-code/OGNet/network.py", line 69, in forward
    x = self.discriminator(x)
  File "/home/yty/anaconda3/envs/svdd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yty/anaconda3/envs/svdd/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/yty/anaconda3/envs/svdd/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yty/anaconda3/envs/svdd/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/yty/anaconda3/envs/svdd/lib/python3.9/site-packages/torch/nn/functional.py", line 1848, in linear
    return torch._C._nn.linear(input, weight, bias)
 (function _print_stack)
Traceback (most recent call last):
  File "/home/yty/lab-code/OGNet/train.py", line 25, in <module>
    model.train(opt.normal_class)
  File "/home/yty/lab-code/OGNet/model.py", line 107, in train
    g_sum_loss.backward()
  File "/home/yty/anaconda3/envs/svdd/lib/python3.9/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/yty/anaconda3/envs/svdd/lib/python3.9/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [4608, 1]], which is output 0 of AsStridedBackward0, is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!`

I already change the` inplace=False` at the relu module in the network.py but still the same message. 

May I ask how to modify the code to successfully run the project?

**Comment by mintaeshkim** [comment]
Same issue happened to me. Any help?

**Comment by mintaeshkim** [comment]
Using later version of PyTorch (in my case, 1.9.1) might cause error.
[zero_grad -> backward -> step]
Try changing train function in model.py as follows.

def train(self, normal_class):
        self.g.train()
        self.d.train()

        # Set optimizators
        g_optim = optim.Adam(self.g.parameters(), lr=self.g_learning_rate)
        d_optim = optim.Adam(self.d.parameters(), lr=self.d_learning_rate)

        fake = torch.ones([self.batch_size], dtype=torch.float32).cuda()
        valid = torch.zeros([self.batch_size], dtype=torch.float32).cuda()
        print('Training until high epoch...')
        for num_epoch in range(self.epoch):
            # print("Epoch {0}".format(num_epoch))
            for i, data in enumerate(self.dataloader):
                input, gt_label = data
                input = input.cuda()

                g_optim.zero_grad()
                d_optim.zero_grad()
                sigma = self.sigma_noise ** 2
                input_w_noise = gaussian(input, 1, 0, sigma)  #Noise
                # Inference from generator
                g_output = self.g(input_w_noise)

                vutils.save_image(input[0:self.image_grids_numbers, :, :, :],
                                  './results/%03d_real_samples_epoch.png' % (num_epoch), nrow=self.n_row_in_grid, normalize=True)
                vutils.save_image(g_output[0:self.image_grids_numbers, :, :, :],
                                  './results/%03d_fake_samples_epoch.png' % (num_epoch), nrow=self.n_row_in_grid, normalize=True)
                vutils.save_image(input_w_noise[0:self.image_grids_numbers, :, :, :],
                                  './results/%03d_noise_samples_epoch.png' % (num_epoch), nrow=self.n_row_in_grid, normalize=True)

                ##############################################
                
                d_fake_output = self.d(g_output)
                d_real_output = self.d(input)
                d_fake_loss = F.binary_cross_entropy(torch.squeeze(d_fake_output), fake)
                d_real_loss = F.binary_cross_entropy(torch.squeeze(d_real_output), valid)
                d_sum_loss = 0.5 * (d_fake_loss + d_real_loss)
                d_sum_loss.backward(retain_graph=True)
                g_optim.zero_grad()

                ##############################################
                g_recon_loss = F.mse_loss(g_output, input)
                g_adversarial_loss = F.binary_cross_entropy(d_fake_output.squeeze(), valid)
                g_sum_loss = (1-self.adversarial_training_factor)*g_recon_loss + self.adversarial_training_factor*g_adversarial_loss
                g_sum_loss.backward()
                
                d_optim.step()
                g_optim.step()

                if i%1 == 0:
                    opts_ft = parse_opts_ft() #opts for phase two

                    if num_epoch == opts_ft.low_epoch:
                        g_model_name = 'g_low_epoch'
                        model_save_path = './models/' + g_model_name
                        torch.save({
                            'epoch': num_epoch,
                            'g_model_state_dict': self.g.state_dict(),
                            'g_optimizer_state_dict': g_optim.state_dict(),
                        }, model_save_path)

                    if num_epoch >= opts_ft.high_epoch:
                        g_model_name = 'g_high_epoch'
                        d_model_name = 'd_high_epoch'
                        model_save_path = './models/' + g_model_name
                        torch.save({
                            'epoch': num_epoch,
                            'g_model_state_dict': self.g.state_dict(),
                            'g_optimizer_state_dict': g_optim.state_dict(),
                        }, model_save_path)

                        model_save_path = './models/' + d_model_name
                        torch.save({
                            'epoch': num_epoch,
                            'd_model_state_dict': self.d.state_dict(),
                            'd_optimizer_state_dict': d_optim.state_dict(),
                        }, model_save_path)

                        print('Epoch {0} / Iteration {1}, before phase two: '.format(num_epoch, i))
                        high_epoch_g_model_name = 'g_high_epoch'
                        high_epoch_d_model_name = 'd_high_epoch'
                        g_model_save_path = './models/' + high_epoch_g_model_name
                        d_model_save_path = './models/' + high_epoch_d_model_name
                        check_auc(g_model_save_path, d_model_save_path,1)
                        fine_tune() #Phase two
                        print('After phase two: ')
                        high_epoch_g_model_name = 'g_high_epoch'
                        high_epoch_d_model_name = 'd_high_epoch'
                        g_model_save_path = './models/' + high_epoch_g_model_name
                        d_model_save_path = './models/' + high_epoch_d_model_name

                        check_auc(g_model_save_path, d_model_save_path,1)
